blank_issues_enabled: false
contact_links:
  - name: Ask Question
    url: https://github.com/livepeer/docs/discussions/new?category=q-a
    about: Ask questions and discuss with other community members
  - name: Request Docs Coverage
    url: https://github.com/livepeer/docs/discussions/new?category=ideas
    about: Request coverage or brainstorm ideas for new docs categories
